
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

# Home assistant
ha_latitude: 63.0000000
ha_longitude: 10.0000000
ha_elevation: 0
ha_external_url: 
ha_internal_url: http://localhost:8124

# MQTT Setup
mqtt_broker: mqtt-sandbox
mqtt_port: 1883
mqtt_client: 
mqtt_user: 
mqtt_passwd:

# Certificate expiry
hass_address: home-assistant.io

# Ping (availability)
ip_xxx: 127.0.0.0
